### ISSUE TITLE
User Login

### ISSUE THREAD

**Issue by Nesschen** [psit4-lamas/PSIT4-LaMaS#18]
As a user, I want to login so that I can view videos.

**Acceptance criteria**:
- [x] verify that a user can login with a username and password
- [ ] if the user's credential is invalid, show an error message

TODOs left:
- [x] ~make login page UI nicer~
- [x] fix double line at the bottom of the login box

**Comment by aleksandar-spasojevic** [comment]
no error message in the component, please take a look @waedi
