### ISSUE TITLE
Check Internalisation of Websites

### ISSUE THREAD

**Issue by Nesschen** [psit4-lamas/PSIT4-LaMaS#56]
Check how we can use different languages in our UI.

**Comment by aleksandar-spasojevic** [comment]
https://medium.freecodecamp.org/setting-up-internationalization-in-react-from-start-to-finish-6cb94a7af725

https://phraseapp.com/blog/posts/react-i18n-best-libraries/

**Comment by aleksandar-spasojevic** [comment]
A new branch feature/internationalization has been created. For the setup, this guide has been used: https://react.i18next.com/legacy-v9/step-by-step-guide
A basic example with lazy language loading, separate translation files and language switcher is implemented.

**Comment by tduong992** [comment]
@tduong992 review PR

**Comment by tduong992** [comment]
the initial code/setup for this feature is now merged into master.
although the following DoD criteria are still not addressed:

### A User Story to be considered "Done" needs to fulfil

- [x] User Story is implemented
- [x] Project builds without errors
- [x] Project deployed on the test environment identical to production platform
- [ ] **Automated functional, non-functional, system and system integration tests passed**
- [x] Tests on devices/browsers listed in the project assumptions passed
- [x] Acceptance tests passing
- [x] Pull Request to `develop` branch created
- [x] Code Review session performed (Quality Assurance, Coding Guidelines and Standards, follow this: https://gist.github.com/cazala/3f6cc82f6b5aa42e210090f7a11f8cb7)
- [x] Issues from Code Review session resolved
- [x] Refactoring completed (Architecture, SonarQube)
- [ ] **Any configuration or build changes documented**
- [ ] **Documentation updated (if exists)**
