### ISSUE TITLE
create subject

### ISSUE THREAD

**Issue by wumacH** [psit4-lamas/PSIT4-LaMaS#66]
As a tutor, i want to create a subject, so that students can get information from there.

**Acceptance criteria**:
- [x] the provided information is saved on the firestore db
- [x] if an error occurre, the user gets informed
- [x] the subject structure is created on db

reminder:
- [x] fix tests

**Comment by wumacH** [comment]
need to write a section in the wiki for manual test of this function

**Comment by tduong992** [comment]
Reply to comment ["need to write a section in the wiki for manual test of this function"](https://github.com/psit4-lamas/PSIT4-LaMaS/issues/66#issuecomment-478362826)

Created a [new ticket](https://github.com/psit4-lamas/PSIT4-LaMaS/issues/110) for this task.
Closing this ticket!
