### ISSUE TITLE
publish lecture

### ISSUE THREAD

**Issue by wumacH** [psit4-lamas/PSIT4-LaMaS#68]
As a tutor, i want to publish a lecture, so that students can see the information.

**Acceptance criteria**:
- [ ] a published lecture is visible for students
- [ ] a lecture is visible for a tutor even if she published or not

**Comment by aleksandar-spasojevic** [comment]
in Absprache mit @wumacH keine Tests erstmal machen; später auf Coverage schauen und dann Tests machen
